feat: lever integration
FilecoinFoundationWeb/filecoin-foundation-site pull request #132
Opened 2022-08-24 15:53 UTC by splumms

Branch includes:
Lever integration for job postings on the Get Involved page

2022-08-24 16:18 UTC, timelytree requested changes
Looks great so far @splumms!! 😊 other than the few review comments, can you also wire up the "view all" button? And lastly, the job posting cards should open in a new tab 👌🏼

2022-08-24 16:18 UTC, timelytree commented on .forestry/front_matter/templates/page-get-involved.yml
> +            default: 2
Default here is `2` but in `get-involved.json` it's set to `3`. Actually this makes sense to me but just pointing it out in case it wasn't intentional :)

2022-08-24 16:18 UTC, timelytree commented on content/pages/get-involved.json
>            },
I think we can remove this entire `display` key?

2022-08-24 16:18 UTC, timelytree commented on store/global.js
> +    const response = await fetch('https://api.lever.co/v0/postings/filecoin?mode=json')
Oh funny you used `fetch()`! I guess maybe Nuxt includes/uses it under the hood?

2022-08-24 16:18 UTC, timelytree commented on store/global.js
> +  jobPostings: {}
Can you set this to `jobPostings: false` as the default state. This way we can do `v-if="jobPostings"` and hide the cards section by default until the load. But only the cards section, the header/blurb/"view all" button can remain visible.

2022-08-24 16:37 UTC, splumms commented on content/pages/get-involved.json
>            },
I removed it but it's needed in general for the block so I've added it in the code with the number_job_posts value instead

2022-08-24 17:17 UTC, splumms commented
@timelytree should be good to go now :)

2022-09-09 19:20 UTC, orvn approved these changes
Approving this merge, but not the one for the FFDW site

2022-09-09 21:29 UTC, merged